# Generated by Django 2.2.5 on 2019-10-01 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(blank=True, null=True, verbose_name='Created')),
                ('time_updated', models.DateTimeField(blank=True, null=True, verbose_name='Updated')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('steam_nickname', models.CharField(max_length=255)),
                ('discord_nickname', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ('-time_created',),
                'abstract': False,
            },
        ),
    ]
